name: OpenAntiRedstoneLag
version: ${version}
api-version: "1.20"
author: Envel
description: Find redstone tick generators

main: org.opencommunity.envel.openantiredstonelag.OpenAntiRedstoneLag

commands:
   rlag:
      description: Get report
      usage: /<command>
      permission: rlag.use
   redstonelag:
      description: Get report
      usage: /<command>
      permission: rlag.use