name: OpenAntiRedstoneLag
version: 1.0
api-version: 1.18
author: Envel
description: Find redstone tick generators

main: org.opencommunity.envel.openantiredstonelag.OpenAntiRedstoneLag

commands:
   rlag:
      description: Get report
      usage: /<command>
      permission: rlag.use
   redstonelag:
      description: Get report
      usage: /<command>
      permission: rlag.use